# Generated by Django 5.2.17 on 2026-09-23 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=48)),
                ('key', models.CharField(max_length=6)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('product_description', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('discovery', 'Discovery'), ('specification', 'Specification'), ('architecture', 'Architecture'), ('planning', 'Planning'), ('ready', 'Ready'), ('implementing', 'Implementing'), ('testing', 'Testing'), ('reviewing', 'Reviewing'), ('pr_created', 'Pull request created'), ('completed', 'Completed'), ('failed', 'Failed'), ('analyzing_failure', 'Analyzing failure'), ('fixing', 'Fixing'), ('human_review_required', 'Human review required')], db_index=True, default='created', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('project_archived', 'Project archived'), ('project_unarchived', 'Project restored'), ('member_added', 'Member added'), ('member_removed', 'Member removed'), ('member_role_changed', 'Member role changed'), ('status_changed', 'Status changed')], max_length=40)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('viewer', 'Viewer')], max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='projects_pr_organiz_8941e0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', '-created_at'], name='projects_pr_organiz_7d8536_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'archived_at'], name='projects_pr_organiz_a0ec73_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_project_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_project_key_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'discovery', 'specification', 'architecture', 'planning', 'ready', 'implementing', 'testing', 'reviewing', 'pr_created', 'completed', 'failed', 'analyzing_failure', 'fixing', 'human_review_required'])), name='project_status_valid'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['project', '-created_at'], name='projects_pr_project_b5fce8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['event_type'], name='projects_pr_event_t_4be36a_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['project_created', 'project_updated', 'project_archived', 'project_unarchived', 'member_added', 'member_removed', 'member_role_changed', 'status_changed'])), name='project_event_type_valid'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'project'], name='projects_pr_user_id_1d5a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'role'], name='projects_pr_project_5b8833_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'maintainer', 'viewer'])), name='project_member_role_valid'),
        ),
    ]
